spring:
  servlet:
    multipart:
      max-file-size: 2MB #单个文件最大容量
      max-request-size: 2MB #上传文件最大容量
  devtools:
    restart:
      enabled: true
      #热部署路径
      additional-paths: src/main/java
  mvc:
    #静态资源请求url
    static-path-pattern: /static/**
    #隐藏表单type
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    username: root
    password: Cyl032512+
    url: jdbc:mysql://42.192.238.52:3306/switchgame?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #关闭thymeleaf缓存
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations: classpath:/static/
mybatis-plus:
  configuration:
    #mp日志文件打印到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名
    map-underscore-to-camel-case: true
  #xml路径
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  #类别名
  type-aliases-package: cn.landsall.switchapi.entity
server:
  servlet:
    #项目根目录
    context-path: /
  port: 8090
#debug: true